package repo;

import fileio.Writer;
import org.json.simple.JSONArray;

import java.io.IOException;

public final class Output {
  private static Writer fileWriter;
  private static JSONArray arrayResult;
  private Output() { }

  /** sets writer and destination JSONArray used when writing outputs */
  public static void setOutput(final Writer writer, final JSONArray jsonArray) {
    fileWriter = writer;
    arrayResult = jsonArray;
  }

  /** adds JSON generated by writer to output array */
  @SuppressWarnings("unchecked")
  public static void write(final int id, final String message) throws IOException {
    arrayResult.add(fileWriter.writeFile(id, "", message));
  }
}
